[build]
  base = "web"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://smartstay-chukaapp.glitch.me/api"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { CI = "false" }

[context.deploy-preview]
  environment = { CI = "false" }

[context.branch-deploy]
  environment = { CI = "false" }
