services:
  - type: web
    name: smartsay-chuka
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://jeanjudy663_db_user:AS2Mst5xQS7bXVtZ@cluster0.ag43qkt.mongodb.net/smartstay?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: smartstay_chuka_secret_key_12345
      - key: NODE_ENV
        value: production
      - key: MPESA_CONSUMER_KEY
        value: W1t82CvAoTMUAtYNAZNGs0GAR2k2coVyT8HETzQtITVqpWmM
      - key: MPESA_CONSUMER_SECRET
        value: QbPw1qmM4tz19JCJwaHwVE7julAUFTSb5ZJBI4Rh8TSGIxJ4auz65erPHZosIQHS
      - key: MPESA_SHORTCODE
        value: "174379"
      - key: MPESA_PASSKEY
        value: test_passkey
      - key: MPESA_ACCOUNT
        value: "0794173314"
      - key: SUBSCRIPTION_FEE
        value: "263"
      - key: CALLBACK_URL
        value: https://smartsay-chuka.onrender.com/api/payments/callback

  - type: static
    name: smartsay-chuka-web
    buildCommand: cd web && npm run build
    staticPublishPath: web/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://smartsay-chuka.onrender.com/api
